server:
  port: 8814

spring:
  data:
    redis:
      repositories:
        enabled: false
  view:
    suffix: .html
    prefix: /
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://121.5.111.133:3306/power?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    #    url: jdbc:mysql://10.8.111.240/power?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/power?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
#    password: a807a807a807
    password: a807807807
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true



